function mms_ld_orbit_sdata_gen_file_v01, input_time_range, probe=probe, filename=cdf_file, errmsg=errmsg

    time_range = time_double(input_time_range)
    year_str = time_string(time_range[0],tformat='YYYY')
    year = float(year_str)
    tr_str = string(year+[0,1],format='(I0)')
    time_range = time_double(tr_str)
    r_var = mms_read_orbit(time_range, probe=probe, ids='cdaweb', errmsg=errmsg)

    time_step = 30d
    common_times = make_bins(time_range+[0,-1]*time_step, time_step)+time_step*0.5
    interp_time, r_var, common_times

    prefix = 'mms'+probe+'_'

;---Init file.
    if file_test(cdf_file) eq 1 then file_delete, cdf_file
    gatt = dictionary($
        'title', 'MMS position', $
        'probe', probe, $
        'text', 'Generated by Sheng Tian, email:ts0110@atmos.ucla.edu' )
    cdf_save_setting, gatt, filename=cdf_file

;---Add time.
    time_var = 'unix_time'
    settings = dictionary($
        'FIELDNAM', 'Time', $
        'UNITS', 'sec', $
        'TEXT', 'Center time of the sampling interval', $
        'VAR_TYPE', 'data' )
    cdf_save_var, time_var, value=common_times, filename=cdf_file, settings=settings

    coord = strlowcase(get_var_setting(r_var, 'coord'))
    r_coord = get_var_data(r_var)
    settings = dictionary($
        'FIELDNAM', 'Spacecraft position', $
        'UNITS', 'Re', $
        'coord', coord, $
        'TEXT', 'Position in '+strupcase(coord), $
        'VAR_TYPE', 'data' )
    cdf_save_var, prefix+'r_'+coord, value=r_coord, filename=cdf_file, settings=settings

;---Done.
    return, cdf_file


end




function mms_ld_orbit_sdata, input_time_range, id=datatype, probe=probe, $
    print_datatype=print_datatype, errmsg=errmsg, $
    local_files=files, file_times=file_times, version=version, $
    local_root=local_root, remote_root=remote_root, $
    return_request=return_request

    compile_opt idl2
    on_error, 0
    errmsg = ''
    retval = ''


;---Check inputs.
    sync_threshold = 0
    if n_elements(probe) eq 0 then probe = 'x'
    if n_elements(local_root) eq 0 then local_root = join_path([default_local_root(),'sdata','mms'])
    if n_elements(remote_root) eq 0 then remote_root = !null
    if n_elements(version) eq 0 then version = 'v01'

    if size(input_time_range[0],type=1) eq 7 then begin
        time_range = time_double(input_time_range)
    endif else begin
        time_range = input_time_range
    endelse

;---Init settings.
    mission_str = 'mms'
    valid_range = mms_valid_range()

    base_name = mission_str+probe+'_orbit_sdata_%Y'+'_'+version+'.cdf'
    local_path = [local_root,'orbit']
    request = dictionary($
        'pattern', dictionary($
            'local_file', join_path([local_path,base_name]), $
            'local_index_file', join_path([local_path,default_index_file()])), $
        'valid_range', time_double(valid_range), $
        'cadence', 'year', $
        'extension', get_file_extension(base_name) )

;---Find files, read variables, and store them in memory.
    if n_elements(files) eq 0 then begin
        files = prepare_files(request=request, errmsg=errmsg, local_files=files, $
            file_times=file_times, time=time_range, nonexist_files=nonexist_files)
    endif
    if n_elements(nonexist_files) ne 0 then begin
        foreach file, request.nonexist_files do begin
            file_time = file.file_time
            local_file = file.local_file
            routine = 'mms_ld_orbit_sdata_gen_file_'+version
            tmp = call_function(routine, file_time, probe=probe, filename=local_file)
        endforeach
        files = prepare_files(request=request, errmsg=errmsg, local_files=files, $
            file_times=file_times, time=time_range, nonexist_files=nonexist_files)
    endif

    if keyword_set(return_request) then return, request
    if n_elements(files) eq 0 then return, '' else return, files

end


tr = ['2016-11-01','2016-11-03']
probe = '1'


file = join_path([homedir(),'test.cdf'])
print, mms_ld_orbit_sdata_gen_file_v01(tr, probe=probe, filename=file)
stop

files = mms_ld_orbit_sdata(tr, probe=probe)
print, files
end
